# Generated by Django 5.0.6 on 2025-01-27 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('donated_blood_group', models.CharField(max_length=10)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.useraccount')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.allevent')),
            ],
        ),
    ]
