# Generated by Django 5.0.6 on 2025-01-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_allevent_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='allevent',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
