# Generated by Django 5.0.6 on 2025-01-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='last_donation',
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='is_available',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='last_donation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
