# Generated by Django 5.0.6 on 2025-01-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_remove_userprofiles_last_donation_userprofiles_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='last_donation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
