# Generated by Django 5.0.6 on 2025-02-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_userprofiles_last_donation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='account/images/'),
        ),
    ]
