# Generated by Django 5.0.6 on 2025-02-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_userprofiles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile/images/'),
        ),
    ]
