# Generated by Django 5.0.6 on 2025-02-02 07:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_userprofiles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
